<a href="https://colab.research.google.com/github/Chandrika-Saha/Machine-Learning-Algos/blob/main/HousePricePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1️⃣ Mount drive
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# 2️⃣ Create kaggle folder in Drive (only once)
!mkdir -p /content/drive/MyDrive/.kaggle

# 3️⃣ Upload kaggle.json manually to:
# /content/drive/MyDrive/.kaggle/kaggle.json

Mounted at /content/drive

In [3]:
from google.colab import files
files.upload()   # upload kaggle.json

Saving kaggle.json to kaggle (1).json

{'kaggle (1).json': b'{"username":"chandrika007","key":"7b701f430b778ececb81ca0fbe658b4f"}'}

In [4]:
!mkdir -p /content/drive/MyDrive/.kaggle
!mv kaggle.json /content/drive/MyDrive/.kaggle/kaggle.json

In [5]:
!ls -la /content/drive/MyDrive/.kaggle

total 1
-rw-------+ 1 root root 68 Feb 17 20:56 kaggle.json

In [6]:
!kaggle -v
!kaggle datasets list -s housing --max-size 1000000

Kaggle API 1.7.4.5
ref                                             title                                 size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------  ------------------------------  ----------  --------------------------  -------------  ---------  ---------------
camnugent/california-housing-prices             California Housing Prices           409382  2017-11-24 03:14:59.677000         289076       1608  0.85294116
schirmerchad/bostonhoustingmlnd                 Boston Housing                        4454  2017-06-11 15:07:11.507000          47512        333  0.8235294
yasserh/housing-prices-dataset                  Housing Prices Dataset                4740  2022-01-12 18:18:46.587000         169354        506  1.0
dansbecker/melbourne-housing-snapshot           Melbourne Housing Snapshot          461423  2018-06-05 12:52:24.087000         204234       1740  0.7058824
harishkumardatalab/housing-price-prediction     Housing Price Prediction              4740  2023-07-07 04:34:24.113000          34050        265  1.0
justinas/housing-in-london                      Housing in London                   173456  2020-04-29 18:43:38.137000          19682        251  1.0
arunjangir245/boston-housing-dataset            Boston Housing dataset               11892  2023-10-15 07:03:26.897000          20713        163  1.0
muhammadbinimran/housing-price-prediction-data  Housing Price Prediction Data       780809  2023-11-21 17:56:32.977000          25608        325  1.0
saurabhbadole/housing-price-data                Housing Price Data                    4762  2024-03-13 05:07:54.503000           5141        125  1.0
sukhmandeepsinghbrar/housing-price-dataset      Housing Price Dataset               798261  2024-04-04 19:45:43.837000          11445        115  1.0
nelgiriyewithana/new-york-housing-market        New York Housing Market             277286  2024-01-06 16:41:00.777000          21312        259  1.0
harrywang/housing                               California Housing Data (1990)      409747  2018-05-10 15:56:31.027000          21066        187  1.0
deepcontractor/miami-housing-dataset            Miami Housing Dataset               665875  2022-01-30 18:18:46.450000           4550         75  1.0
shubhammeshram579/house                         Housing price prediction             11881  2023-04-19 09:37:25.517000           5225         75  1.0
altavish/boston-housing-dataset                 Boston housing dataset               11983  2017-10-27 12:17:34.970000          83968        239  0.5882353
rukenmissonnier/final-house                      Housing Market & Prices            147049  2023-09-22 08:11:29.100000           3805         51  1.0
kathuman/housing                                Housing                             409382  2022-09-29 10:21:23.247000           1746         30  1.0
arnavgupta1205/usa-housing-dataset              USA Housing Dataset                   6427  2025-02-05 10:28:13.400000           2599         40  1.0
mssmartypants/paris-housing-price-prediction    Paris Housing Price Prediction      275823  2021-06-30 13:31:27.193000          13381         84  0.9117647
faryarmemon/usa-housing-market-factors          U.S. Housing Market Factors          32990  2022-08-03 02:19:31.937000           4780         75  1.0

In [7]:
# 3️⃣ Download dataset ONLY if not already downloaded
import os

if not os.path.exists("/content/drive/MyDrive/new-york-housing-market"):
    !kaggle datasets download -d nelgiriyewithana/new-york-housing-market -p /content/drive/MyDrive/
    !unzip /content/drive/MyDrive/new-york-housing-market.zip -d /content/drive/MyDrive/new-york-housing-market

Dataset URL: https://www.kaggle.com/datasets/nelgiriyewithana/new-york-housing-market
License(s): other
Downloading new-york-housing-market.zip to /content/drive/MyDrive
  0% 0.00/271k [00:00<?, ?B/s]
100% 271k/271k [00:00<00:00, 15.1MB/s]
Archive:  /content/drive/MyDrive/new-york-housing-market.zip
  inflating: /content/drive/MyDrive/new-york-housing-market/NY-House-Dataset.csv

In [8]:
# Imports
import pandas as pd

In [9]:
filepath = "/content/drive/MyDrive/new-york-housing-market/NY-House-Dataset.csv"
df = pd.read_csv(filepath)
df.head()

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.0,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.0,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.0,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.0,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.0,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856

In [16]:
df.shape

(4801, 17)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4801 entries, 0 to 4800
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   BROKERTITLE                  4801 non-null   object
 1   TYPE                         4801 non-null   object
 2   PRICE                        4801 non-null   int64
 3   BEDS                         4801 non-null   int64
 4   BATH                         4801 non-null   float64
 5   PROPERTYSQFT                 4801 non-null   float64
 6   ADDRESS                      4801 non-null   object
 7   STATE                        4801 non-null   object
 8   MAIN_ADDRESS                 4801 non-null   object
 9   ADMINISTRATIVE_AREA_LEVEL_2  4801 non-null   object
 10  LOCALITY                     4801 non-null   object
 11  SUBLOCALITY                  4801 non-null   object
 12  STREET_NAME                  4801 non-null   object
 13  LONG_NAME                    4801 non-null   object
 14  FORMATTED_ADDRESS            4801 non-null   object
 15  LATITUDE                     4801 non-null   float64
 16  LONGITUDE                    4801 non-null   float64
dtypes: float64(4), int64(2), object(11)
memory usage: 637.8+ KB

In [18]:
df.describe(include='object')

,BROKERTITLE,TYPE,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS
count,4801,4801,4801,4801,4801,4801,4801,4801,4801,4801,4801
unique,1036,13,4582,308,4583,29,11,21,174,2731,4550
top,Brokered by COMPASS,Co-op for sale,856 Washington Ave Apt 6C,"Brooklyn, NY 11235","856 Washington Ave Apt 6CBrooklyn, NY 11238",United States,New York,New York,Manhattan,2,"61-20 Grand Central Pkwy, Forest Hills, NY 113..."
freq,456,1450,3,102,3,2484,2505,1016,979,20,4

In [14]:
df.describe()

,PRICE,BEDS,BATH,PROPERTYSQFT,LATITUDE,LONGITUDE
count,4.801000e+03,4801.000000,4801.000000,4801.000000,4801.000000,4801.000000
mean,2.356940e+06,3.356801,2.373861,2184.207862,40.714227,-73.941601
std,3.135525e+07,2.602315,1.946962,2377.140894,0.087676,0.101082
min,2.494000e+03,1.000000,0.000000,230.000000,40.499546,-74.253033
25%,4.990000e+05,2.000000,1.000000,1200.000000,40.639375,-73.987143
50%,8.250000e+05,3.000000,2.000000,2184.207862,40.726749,-73.949189
75%,1.495000e+06,4.000000,3.000000,2184.207862,40.771923,-73.870638
max,2.147484e+09,50.000000,50.000000,65535.000000,40.912729,-73.702450